### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by devjohony** [devjohony/furima-37766#20]
https://frozen-island-83256.herokuapp.com/
本番環境URL

Basic認証のIDとパスワード        name "admin"       pass "8888"

出品者用のメールアドレスとパスワード
mail     example@test.com
pass    111111a

購入者用のメールアドレスとパスワード
mail      example@test2.com
pass     222222a

**Comment by shodai-ito** [comment]
@devjohony さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
`商品詳細表示機能`
- [x] **商品詳細表示ページは、ログイン状況や商品の販売状況に関係なく、誰でも見ることができること**
ログイン状態で自身の出品した商品詳細ページへ遷移できません。
<img width="717" alt="スクリーンショット 2022-05-13 15 00 44" src="https://user-images.githubusercontent.com/62537107/168221275-ca859607-1d2e-4afd-8160-2ea2981ea8d6.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by devjohony** [comment]
修正しました

**Comment by shodai-ito** [comment]
@devjohony さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
`商品詳細機能`
- [x]  **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されること**
出品者名の欄に表示されているのが商品名になっています。
<img width="927" alt="スクリーンショット 2022-05-13 17 14 20" src="https://user-images.githubusercontent.com/62537107/168242415-3a31e6b5-4157-4ccf-9572-053d88164ba3.png">

`商品編集機能`
- [x] **商品名やカテゴリーの情報など、すでに登録されている商品情報は商品情報編集画面を開いた時点で表示されること（商品画像・販売手数料・販売利益に関しては、表示されない状態で良い）**
編集ページを開いた際、商品説明の欄が空欄になっています。

- [x] **編集が完了したら、商品詳細表示ページに遷移し、変更された商品情報が表示されること**
商品説明を編集しても反映されません。

`商品購入機能`
- [x] **商品出品時に登録した情報のうち、「商品名・商品画像・価格・配送料の負担」の4つの情報が、見本アプリと同様の形で表示されること**
商品名を表示する箇所の内容が、商品説明になっております。

- [x] **建物名は任意であること**
建物名が必須になっております。
<img width="356" alt="スクリーンショット 2022-05-13 17 16 46" src="https://user-images.githubusercontent.com/62537107/168243043-62042a5e-085b-4f7d-8c42-fd3967914c18.png">

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by devjohony** [comment]
修正しました

**Comment by snkw-works** [comment]
@devjohony さん、大変お待たせいたしました。ご提出ありがとうございます‼︎
正常に動作することが確認できました！　**LGTM** です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）

【お願い】
現在、アプリ内にカリキュラムの画像を用いた投稿がございます。
こちら利用規約にもあります通り、カリキュラム内容の漏洩に繋がりかねませんので、お手数ですが削除もしくは画像の差し替えをお願い致します。

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**

**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/54050089/164166779-9eca4a1e-955a-4d55-bfa3-c0ff25e73e87.png)
